#!/bin/bash

getdevice() {
	#based on https://unix.stackexchange.com/questions/136781/how-to-get-device-filename-from-lsusb-output-or-by-device-path
	idV=${1%:*}
	idP=${1#*:}
	for path in $(dirname $(find -L /sys/bus/usb/devices/ -maxdepth 2 -name "idVendor")); do
	if grep -q $idV $path/idVendor && grep -q $idP $path/idProduct; then
			echo $path
		fi
	done
}

get_blockdev() {
	# This can match twice so add `-m 1` to grep to only match once
	SYSFS_BLOCK_RELATIVE=$(realpath --relative-base=$1 /sys/block/* | grep -vm 1 "^/")
	basename $SYSFS_BLOCK_RELATIVE 2>/dev/null
}

print_help() {
	cat << EOF
To switch the SD card to USB run:
$0 1
To switch the SD card to SBC run:
$0 0
To print the block dev run:
$0 p

If you have multiple devices run either of the above.
Then run with the last param the same as above:
$0 \$(Your USB number) 0

NOTE:
When printing the block device the script waits until the device exists

Examples:
# $0 0
Uisng device /sys/bus/usb/devices/3-4

# $0 0
Uisng device /sys/bus/usb/devices/3-4
Already off.

# $0 p
/dev/sda

# $0 0
Multiple devices found! Pass a usb number as param 1...
Usb num: 3-4
Usb num: 3-1

# $0 3-1 0
Uisng device /sys/bus/usb/devices/3-1
EOF
	exit 1
}

export DEVICES=$(getdevice 0bda:0316)
if echo $DEVICES | grep -q " "; then
	if [ $# -eq 2 ]; then
		for dev in $DEVICES; do
			if echo $dev | grep -q $1; then
				export DEVICE=$dev
			fi
		done
		if [ -z $DEVICE ]; then
			echo "Device not found. Pass a usb number as param 1..."
			for dev in $DEVICES; do
				echo "Usb num:" $(basename $dev)
			done
			exit 1
		fi
	else
		echo "Multiple devices found! Pass a usb number as param 1..."
		for dev in $DEVICES; do
			echo "Usb num:" $(basename $dev)
		done
		exit 1
	fi
else
		export DEVICE=$DEVICES
fi

if [ -z "$DEVICES" ]; then
	echo "No devices found ;("
	exit 1
fi

if [ $(eval echo \${$#}) == 'p' ]; then
	while true; do
		DEVNAME=$(get_blockdev $DEVICE) && break
	done
	echo /dev/$DEVNAME
	exit 0
fi

echo "Uisng device" $DEVICE

DEVNAME=$(get_blockdev $DEVICE)
if [[ ${DEVNAME} ]]; then
	echo "With devpath of /dev/"$DEVNAME
fi

export USB_NUM=$(basename $DEVICE)

echo 0 | sudo tee ${DEVICE}/power/autosuspend_delay_ms &>/dev/null
echo auto | sudo tee ${DEVICE}/power/control &>/dev/null

if [ $(eval echo \${$#}) == '1' ]; then
	echo $USB_NUM | sudo tee /sys/bus/usb/drivers/usb/bind &>/dev/null || echo "Already on"
elif [ $(eval echo \${$#}) == '0' ]; then
	echo $USB_NUM | sudo tee /sys/bus/usb/drivers/usb/unbind &>/dev/null|| echo "Already off."
else
	print_help
fi
